batch_size: 32
decoder_conv_t_filters:
- 1
decoder_conv_t_kernel_size:
- 3
decoder_conv_t_strides:
- 1
encoder_conv_filters:
- 1
encoder_conv_kernel_size:
- 3
encoder_conv_strides:
- 1
input_dim: !!python/tuple
- 1
- 28
- 28
model: !!python/name:layers.autoencoder.AutoEncoder ''
use_batch_norm: false
use_dropout: false
z_dim: 2
